# Generated by Django 3.2.4 on 2022-05-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_companies_tenders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenders',
            old_name='user_id',
            new_name='company_id',
        ),
    ]
