# Generated by Django 3.2.4 on 2022-05-09 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_rename_user_id_tenders_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
