# Generated by Django 4.0 on 2022-05-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_tenderappliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderappliers',
            name='given_to',
            field=models.BooleanField(default=False),
        ),
    ]
